### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by kankaristo** [lexicalunit/multi-wrap-guide#14]
I started getting this after updating the package to 0.21.0.
1. Open a file
2. Close the tab
3. Error

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [multi-wrap-guide](https://github.com/lexicalunit/multi-wrap-guide) package, v0.21.0
### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At /home/sami/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide.coffee:49

TypeError: Cannot read property 'destroy' of undefined
  at /home/sami/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide.coffee:49:5
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/opt/atom/resources/app.asar/src/text-editor.js:273:27)
  at TextEditor.module.exports.Model.destroy (/opt/atom/resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (/opt/atom/resources/app.asar/src/pane.js:444:18)
  at HTMLDivElement.<anonymous> (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -7:41.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "docblockr",
      "linter-luacheck",
      "atom-ctags",
      "log-console",
      "wrap-guide",
      "clipboard-plus"
    ],
    "excludeVcsIgnoredPaths": false,
    "destroyEmptyPanes": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*build/*",
      "runtime/*"
    ]
  },
  "multi-wrap-guide": {
    "columns": [
      80,
      100,
      120
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
auto-detect-indentation, v0.4.2
autocomplete-clang, v0.7.0
autocomplete-emojis, v2.2.2
autocomplete-glsl, v0.2.3
autocomplete-paths, v1.0.2
autocomplete-python, v0.5.1
branch-status, v0.8.1
build, v0.36.1
external-open, v0.5.4
file-icons, v1.5.8
file-watcher, v0.3.1
flex-tool-bar, v0.4.2
git-log, v0.4.1
gutter-shadow, v0.5.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-brainfuck, v0.1.0
language-gitignore, v0.2.0
language-glsl, v2.0.0
language-ini, v1.10.0
language-latex, v0.6.1
language-lisp, v0.1.2
language-log, v0.4.0
language-lua, v0.9.4
language-qml, v1.0.0
language-qtpro, v0.5.0
language-r, v0.2.0
language-restructuredtext, v0.6.0
language-svg, v0.8.0
language-swig-wrapper, v0.0.0
language-x86, v0.1.0
line-diff-details, v1.1.1
line-jumper, v0.14.1
linter, v1.1.0
linter-clang, v2.26.0
linter-coffeelint, v0.3.2
linter-csslint, v0.0.14
linter-flake8, v1.4.2
linter-jscs, v1.12.0
linter-jshint, v0.1.7
linter-less, v2.0.3
linter-lua, v0.1.6
linter-pylint, v0.2.2
linter-shellcheck, v0.0.8
linter-xmllint, v0.0.7
minimap, v4.10.1
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
minimap-selection, v4.3.0
multi-wrap-guide, v0.21.0
open-recent, v2.2.4
pigments, v0.8.1
pretty-json, v0.4.1
project-colorize, v0.2.0
project-manager, v1.15.10
revert-buffer, v0.5.0
svg-preview, v0.6.0
tab-smart-sort, v0.1.4
toggle-packages, v1.0.1
tool-bar, v0.1.8
trailing-spaces, v0.3.2
tree-view-breadcrumb, v0.6.0
tree-view-open-files, v0.2.4
wakatime, v4.0.11
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by kankaristo** [comment]
This seems to have gone away after restarting Atom...

I guess the old version was still somehow active after updating to the new version. I've had this happen with some other packages as well, producing some really weird bugs.

I'll close this and report back if it happens again. :)

**Comment by lexicalunit** [comment]
Just in case I added undefined guards for the `destroy` calls. Hopefully it won't happen again :+1:
