### ISSUE TITLE
Failed to activate the multi-wrap-guide package

### ISSUE THREAD

**Issue by ryran** [lexicalunit/multi-wrap-guide#16]
[Enter steps to reproduce below:]
1. First noticed in Atom 1.2.0 
2. Have been using multi-wrap-guide forever ... but now it fails loading

**Atom Version**: 1.2.2
**System**: "Fedora release
**Thrown From**: [multi-wrap-guide](https://github.com/lexicalunit/multi-wrap-guide) package, v0.23.1
### Stack Trace

Failed to activate the multi-wrap-guide package

```
At Cannot find module 'sub-atom'

Error: Cannot find module 'sub-atom'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports.activate (/home/rsaw/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide.coffee:56:17)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:170:19)
    at /usr/share/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:512:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:333:19
    at /usr/share/atom/resources/app.asar/src/config.js:588:20
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:773:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:565:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:226:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:343:12)
    at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:162:14)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -0:08.3.0 settings-view:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "indentation-indicator",
      "symbols-view",
      "wrap-guide",
      "whitespace"
    ]
  },
  "multi-wrap-guide": {
    "columns": [
      73
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-python, v0.10.4
autohide-tree-view, v0.25.1
highlight-selected, v0.11.1
indent-guide-improved, v1.4.3
minimap, v4.16.1
minimap-autohide, v0.10.1
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
multi-wrap-guide, v0.23.1
python-yapf, v0.9.0
symbols-tree-view, v0.10.1
tab-control, v0.6.8

# Dev
No dev packages
```

**Comment by ryran** [comment]
Also, even after disabling, I can't get the default wrap-guide back. Am I an idiot? I don't see anything about it in the settings. Only "Preferred Line Length", which I've set to 60 ... but for some reason when I do reflow-selection it's wrapping at 120. Sigh. Any help appreciated. (I use this a dozen times a day in my work, typing comments to clients.)

EDIT: I figured that last part out at least. Yay. Modified `editor: preferredLineLength` in my `config.cson` for the appropriate file types.

**Comment by lexicalunit** [comment]
Hrmm, it seems like the `sub-atom` dependency didn't install correctly for some reason. Can you try going to your package directory where `multi-wrap-guide` is installed (`~/.atom/packages/multi-wrap-guide` on *nix systems) and running `npm install --verbose` and pasting the output of that here? Also maybe `npm list` too?

As for getting the old wrap line back, you'll need to enable the `wrap-guide` package in your settings again. The `multi-wrap-guide` disables that package to prevent conflicts, but re-enabling it should resolve things.

**Comment by hsmith** [comment]
# RESOLVED

I was running a very out of date version of Atom.

---

After installing the package I get this message:
`Failed to activate the multi-wrap-guide package
this.editorElement.onDidChangeScrollLeft is not a function`

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.5
**Thrown From**: [multi-wrap-guide](https://github.com/lexicalunit/multi-wrap-guide) package, v0.25.2

### Stack Trace

Failed to activate the multi-wrap-guide package

```
At this.editorElement.onDidChangeScrollLeft is not a function

TypeError: this.editorElement.onDidChangeScrollLeft is not a function
    at MultiWrapGuideView.module.exports.MultiWrapGuideView.handleEvents (/home/hsmith/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.coffee:84:30)
    at MultiWrapGuideView.module.exports.MultiWrapGuideView.initialize (/home/hsmith/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.coffee:31:6)
    at MultiWrapGuideView.View (/home/hsmith/.atom/packages/multi-wrap-guide/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new MultiWrapGuideView (/home/hsmith/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.coffee:7:3)
    at /home/hsmith/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide.coffee:85:31
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:276:9)
    at Object.module.exports.activate (/home/hsmith/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide.coffee:84:20)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:245:19)
    at /usr/share/atom/resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:169:15)
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "autocomplete-atom-api",
      "autocomplete-css",
      "autocomplete-html",
      "autocomplete-plus",
      "autocomplete-snippets",
      "grammar-selector",
      "bracket-matcher",
      "autoflow",
      "spell-check",
      "whitespace",
      "wrap-guide",
      "wrap-guide"
    ],
    "projectHome": "~/development",
    "ignoredNames": [
      ".git",
      ".pyc",
      "core",
      "bin",
      "share"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "followSymlinks": false
  },
  "multi-wrap-guide": {
    "rows": [
      60,
      80
    ],
    "locked": true
  }
}
```

### Installed Packages

``` coffee
# User
language-bazel, v0.3.2
language-cmake, v0.2.0
language-cpp14, v0.6.2
language-vue, v0.19.0
linter-cpplint, v1.0.1
multi-wrap-guide, v0.25.2

# Dev
No dev packages
```

### npm install --verbose

```
hsmith@hsmith-m4800:~/.atom/packages/multi-wrap-guide$ npm install -verbose
npm info it worked if it ends with ok
npm verb cli [ '/home/hsmith/.nvm/versions/node/v5.9.0/bin/node',
npm verb cli   '/home/hsmith/.nvm/versions/node/v5.9.0/bin/npm',
npm verb cli   'install',
npm verb cli   '-verbose' ]
npm info using npm@3.7.3
npm info using node@v5.9.0
npm verb correctMkdir /home/hsmith/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/hsmith/.npm/_locks/staging-c4280c57528d3e8c.lock for /home/hsmith/.atom/packages/multi-wrap-guide/node_modules/.staging
npm verb unlock done using /home/hsmith/.npm/_locks/staging-c4280c57528d3e8c.lock for /home/hsmith/.atom/packages/multi-wrap-guide/node_modules/.staging
npm info lifecycle multi-wrap-guide@0.25.2~preinstall: multi-wrap-guide@0.25.2
npm info linkStuff multi-wrap-guide@0.25.2
npm verb linkBins multi-wrap-guide@0.25.2
npm verb linkMans multi-wrap-guide@0.25.2
npm info lifecycle multi-wrap-guide@0.25.2~install: multi-wrap-guide@0.25.2
npm info lifecycle multi-wrap-guide@0.25.2~postinstall: multi-wrap-guide@0.25.2
npm info lifecycle multi-wrap-guide@0.25.2~prepublish: multi-wrap-guide@0.25.2
npm verb exit [ 0, true ]
npm info ok 
```

**Comment by pstadler** [comment]
I'm having this issue running Atom 1.12.5.

```
ReferenceError: editor is not defined
    at MultiWrapGuideView.module.exports.MultiWrapGuideView.initialize (/Users/pstadler/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.coffee:29:41)
    at MultiWrapGuideView.View [as constructor] (/Users/pstadler/.atom/packages/multi-wrap-guide/node_modules/space-pen/lib/space-pen.js:184:25)
    at new MultiWrapGuideView (/Users/pstadler/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.coffee:6:7)
    at /Users/pstadler/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide.coffee:85:31
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:9)
    at Object.activate (/Users/pstadler/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide.coffee:84:20)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:506:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:792:28
```

Thank you very much for your effort 🍻

**Comment by lexicalunit** [comment]
@pstadler What version of multi-wrap-guide do you have installed?

**Comment by pstadler** [comment]
Sorry for the late response. This happened with 0.26. On my other host I see that the version has been pinned to 0.25.2 and runs w/o any problems. Maybe my sync settings were messing things up.

I'd close this for now. Sorry for the fuss.

**Comment by lexicalunit** [comment]
@pstadler My apologies! There's a problem with v0.26. I unpublished it but you probably downloaded it before I did. Stay on 0.25.2 for now. When the next version of Atom comes the upgrade path should skip v0.26 automatically. It was just that brief period of time before I realized the problem with that version where people could install it.

**Comment by pstadler** [comment]
That explains everything 😅

**Comment by wedi** [comment]
Hi!
I am having this issue as well with multi-wrap-guide _0.25.2_. See version info and stack trace below.

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Mac OS X 10.11.6
**Thrown From**: [multi-wrap-guide](https://github.com/lexicalunit/multi-wrap-guide) package, v0.25.2


### Stack Trace

Failed to activate the multi-wrap-guide package

```
At editor is not defined

ReferenceError: editor is not defined
  at MultiWrapGuideView.module.exports.MultiWrapGuideView.initialize (/Users/dirk/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.coffee:29:41)
  at MultiWrapGuideView.View [as constructor] (/Users/dirk/.atom/packages/multi-wrap-guide/node_modules/space-pen/lib/space-pen.js:184:25)
  at new MultiWrapGuideView (/Users/dirk/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.coffee:7:3)
  at /Users/dirk/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide.coffee:85:31
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:9)
  at Object.activate (/Users/dirk/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide.coffee:84:20)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:529:29
  at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:506:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:792:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "spell-check",
      "wrap-guide"
    ],
    "projectHome": "/Users/dirk/dev",
    "telemetryConsent": "limited"
  },
  "multi-wrap-guide": {
    "enabled": false
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v1.3.0 (inactive)
dash, v1.7.0 (inactive)
editorconfig, v2.0.5 (inactive)
hard-wrap, v1.1.0 (inactive)
highlight-selected, v0.11.2 (inactive)
indent-guide-improved, v1.4.11 (inactive)
language-nesc, v0.2.0 (inactive)
markdown-lists, v0.0.2 (inactive)
multi-wrap-guide, v0.25.2 (inactive)
open-recent, v5.0.0 (inactive)
platformio-ide-terminal, v2.2.2 (inactive)
sort-lines, v0.14.0 (inactive)
split-diff, v1.1.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```
