### ISSUE TITLE
Does not play nice with atom-narrow

### ISSUE THREAD

**Issue by paradox460** [lexicalunit/multi-wrap-guide#34]
When both [atom-narrow](https://github.com/t9md/atom-narrow) and multi-wrap-guide are loaded at once, atom-narrow is rendered unusable. multi-wrap-guide throws an error whenever a narrow window is open, halting the narrow window's rendering.

```
/Users/jeffsandberg/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.js:154 
Uncaught (in promise) TypeError: Cannot set property 'onclick' of null
    at MultiWrapGuideView.handleEvents (/Users/jeffsandberg/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.js:103:19)
    at new MultiWrapGuideView (/Users/jeffsandberg/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.js:26:10)
    at /Users/jeffsandberg/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide.js:48:31
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:729:22
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:583:34
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:584:19
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didAddPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:270:24)
    at Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:632:48)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:574:18)
    at Ui.<anonymous> (/Users/jeffsandberg/.atom/packages/narrow/lib/ui.js:463:10)
    at Generator.next (<anonymous>)
    at step (/Users/jeffsandberg/.atom/packages/narrow/lib/ui.js:1:12)
    at /Users/jeffsandberg/.atom/packages/narrow/lib/ui.js:1:12
    at Ui.<anonymous> (/Users/jeffsandberg/.atom/packages/narrow/lib/ui.js:1:12)
    at Search.<anonymous> (/Users/jeffsandberg/.atom/packages/narrow/lib/provider/provider-base.js:268:21)
    at Generator.next (<anonymous>)
    at step (/Users/jeffsandberg/.atom/packages/narrow/lib/provider/provider-base.js:1:12)
```

**Comment by lexicalunit** [comment]
Definitely a bug; sorry you're experiencing this! I think this is because narrow windows don't have the typical gutter I'm expecting so I need to put a defensive guard around that code.

**Comment by lexicalunit** [comment]
Please give v1.1.4 a try.

**Comment by paradox460** [comment]
Can confirm it works
