### ISSUE TITLE
Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by adammw** [lexicalunit/multi-wrap-guide#7]
**Atom Version**: 0.207.0
**System**: Mac OS X 10.9.5
**Thrown From**: [multi-wrap-guide](https://github.com/lexicalunit/multi-wrap-guide) package, v0.13.0

It's not clear how to install https://github.com/atom/atom-space-pen-views... am I missing something?
### Stack Trace

Failed to load the multi-wrap-guide package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/adammw/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.coffee:10:10)
    at Object.<anonymous> (/Users/adammw/.atom/packages/multi-wrap-guide/lib/multi-wrap-guide-view.coffee:673:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "metrics",
      "autocomplete-paths",
      "travis-ci-status",
      "term",
      "vim-mode",
      "gist-it",
      "atom-beautify"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "multi-wrap-guide": {
    "columns": [
      80,
      120
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-handlebars, v0.5.0
atom-jasmine, v0.5.0
atom-ternjs, v0.6.4
atomatigit, v1.5.3
auto-update-packages, v1.0.0
change-case, v0.6.0
color-picker, v2.0.4
command-logger, v0.23.0
editor-stats, v0.17.0
file-icons, v1.5.7
file-types, v0.4.0
html2haml, v0.10.0
indentation-indicator, v0.5.1
language-haml, v0.21.0
linter, v0.12.6
linter-jshint, v0.1.6
linter-rubocop, v0.2.7
linter-scss-lint, v1.0.4
minimap, v4.9.4
minimap-git-diff, v4.1.3
multi-wrap-guide, v0.13.0
project-manager, v1.15.10
tabs, v0.67.0

# Dev
No dev packages
```

**Comment by lexicalunit** [comment]
Somehow I completely forgot to add the dependency into `package.json`! My bad. Try installing multi-wrap-guide version 0.14.0. It should work now.
